"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowUpRight, CheckCircle2, FileText, Package, Plus, Search } from "lucide-react";
import { useApp } from "@/components/app-provider";
import { Badge, Button, Card, DataTable, Drawer, EmptyState, FieldPair, SearchField } from "@/components/ui";
import { navItems,routeHref } from "./shell";
import { customerSummary } from "@/lib/mock/customers";
import { invoiceStatus, outstanding, paidAmount } from "@/lib/mock/invoices";
import { stockStatus } from "@/lib/mock/inventory";
import { date,daysBetween,money } from "@/lib/utils/format";
import type { Insight } from "@/lib/types";
export function DetailPanel(){const app=useApp();const {data,panel,close,t,lang,open,local}=app;if(!panel||!data)return null;
 let title=t("evidence");let content:React.ReactNode=null;
 if(panel.kind==="invoice"){
 const invoice=data.invoices.find(i=>i.id===panel.id);if(!invoice)return null;const customer=data.customers.find(c=>c.id===invoice.customerId)!;const status=invoiceStatus(invoice);title=t("invoiceDetails");const insight=data.insights.find(i=>i.targetId===invoice.id)??{...data.insights[0],id:`FOLLOW-${invoice.id}`,targetId:invoice.id,title:{en:`Follow up on ${invoice.id}`,hi:`${invoice.id} पर फॉलो-अप`,hinglish:`${invoice.id} par follow-up`},summary:{en:customer.name,hi:customer.name,hinglish:customer.name},recommendation:{en:`Confirm a payment date with ${customer.name}.`,hi:`${customer.name} से भुगतान की तारीख तय करें।`,hinglish:`${customer.name} se payment date confirm karein.`}};
 content=<><div className="detail-title"><div><span className="eyebrow">{t("invoice")}</span><h2 className="mono">{invoice.id}</h2></div><Badge status={status}/></div><button className="record-link customer-detail-link" onClick={()=>open({kind:"customer",id:customer.id})}>{customer.name}<ArrowUpRight size={14}/></button><div className="field-grid"><FieldPair label={t("date")}>{date(invoice.date,lang)} 2026</FieldPair><FieldPair label={t("dueDate")}>{date(invoice.dueDate,lang)} 2026</FieldPair></div><DataTable headers={[t("items"),t("quantity"),t("amount")]}>{invoice.items.map(item=><tr key={item.productId}><td>{data.products.find(p=>p.id===item.productId)?.name}<small className="block muted">{money(item.unitPrice)} / {t("units")}</small></td><td>{item.quantity}</td><td className="numeric">{money(item.gross)}</td></tr>)}</DataTable><div className="invoice-totals">{([["subtotal",invoice.subtotal],["tax",invoice.tax],["total",invoice.total],["paid",paidAmount(invoice)],["outstanding",outstanding(invoice)]] as const).map(([label,amount])=><div key={label}><span>{t(label)}</span><strong>{label==="subtotal"||label==="tax"?new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(amount):money(amount)}</strong></div>)}</div><p className="small muted">{t("taxNote")}</p><div className="detail-insight"><span className="eyebrow">{t("invoiceInsight")}</span><h3>{status==="paid"?t("invoicePaid"):status==="overdue"?t("unpaidDays",{amount:money(outstanding(invoice)),days:daysBetween(invoice.dueDate)}):t("invoicePending",{date:date(invoice.dueDate,lang)})}</h3>{outstanding(invoice)>0&&<><p>{insight.recommendation[lang]}</p><ActionForm insight={insight}/><Button variant="ghost" onClick={()=>app.setStatus(insight.id,"handled")}>{app.status(insight.id)==="handled"?t("handled"):t("markHandled")}</Button></>}</div><h3>{t("paymentHistory")}</h3>{data.payments.filter(p=>p.invoiceId===invoice.id).map(p=><div className="list-row" key={p.id}><span>{p.id}<small>{date(p.date,lang)} · {p.method.toUpperCase()}</small></span><strong>{money(p.amount)}</strong></div>)}{paidAmount(invoice)===0&&<p className="muted">{t("noPayments")}</p>}</>;
 }else if(panel.kind==="evidence"){
 content=<div className="evidence-panel"><span className="eyebrow">{t("linkedEvidence")}</span><p className="muted">{t("sampleData")} · {t("demoDate")}</p>{panel.id.split(",").map(id=>{const e=data.evidence.find(v=>v.id===id);if(!e)return null;const inv=e.type==="invoice"?data.invoices.find(v=>v.id===e.entityId):undefined;const product=e.type==="inventory"?data.products.find(v=>v.id===e.entityId):undefined;const expense=e.type==="expense"?data.expenses.find(v=>v.id===e.entityId):undefined;return <Card key={e.id} className="evidence-record"><div className="evidence-title"><FileText size={20}/><strong>{e.label}</strong></div>{inv&&<><FieldPair label={t("customer")}>{data.customers.find(c=>c.id===inv.customerId)?.name}</FieldPair><FieldPair label={t("amount")}>{money(inv.total)}</FieldPair><FieldPair label={t("dueDate")}>{date(inv.dueDate,lang)} 2026</FieldPair><FieldPair label={t("paid")}>{money(paidAmount(inv))}</FieldPair><Button onClick={()=>open({kind:"invoice",id:inv.id})}>{t("invoiceDetails")}<ArrowUpRight size={14}/></Button></>}{product&&<><FieldPair label={t("product")}>{product.name}</FieldPair><FieldPair label={t("currentStock")}>{product.stock} {t("units")}</FieldPair><FieldPair label={t("reorderLevel")}>{product.reorderLevel}</FieldPair><FieldPair label={t("velocity")}>{product.dailySales} {t("perDay")}</FieldPair><FieldPair label={t("daysCover")}>{Math.floor(product.stock/product.dailySales)}</FieldPair><Button onClick={()=>open({kind:"product",id:product.id})}>{t("productDetails")}<ArrowUpRight size={14}/></Button></>}{expense&&<><FieldPair label={t("thisMonth")}>{money(expense.amount)}</FieldPair><FieldPair label={t("previousMonth")}>{money(19758)}</FieldPair><FieldPair label={t("change")}>+24%</FieldPair><p>{data.insights[2].why[lang]}</p></>}{e.documentId&&<button className="text-link evidence-document" onClick={()=>open({kind:"document",id:e.documentId!})}>{t("documentDetails")}<ArrowUpRight size={14}/></button>}</Card>;})}</div>;
 }else if(panel.kind==="customer"){
 const c=data.customers.find(c=>c.id===panel.id);if(!c)return null;title=t("customerDetails");const s=customerSummary(c.id);content=<><h2>{c.name}</h2><p className="muted">{c.city}</p><div className="detail-metrics"><FieldPair label={t("totalPurchases")}>{money(s.purchases)}</FieldPair><FieldPair label={t("outstanding")}>{money(s.outstanding)}</FieldPair></div><FieldPair label={t("contact")}>{c.contact}</FieldPair><FieldPair label={t("phone")}>{c.phone}</FieldPair>{c.id==="CUS-1001"&&<div className="detail-insight">{t("largestOutstanding")}</div>}<h3>{t("purchaseHistory")}</h3>{s.invoices.length?s.invoices.map(i=><button className="list-row" key={i.id} onClick={()=>open({kind:"invoice",id:i.id})}><span>{i.id}<small>{date(i.date,lang)}</small></span><span><strong>{money(i.total)}</strong><Badge status={invoiceStatus(i)}/></span><ArrowUpRight size={14}/></button>):<p>{t("noHistory")}</p>}<h3>{t("paymentHistory")}</h3>{s.payments.length?s.payments.map(p=><div className="list-row" key={p.id}><span>{p.id}<small>{p.invoiceId} · {date(p.date,lang)}</small></span><strong>{money(p.amount)}</strong></div>):<p className="muted">{t("noPayments")}</p>}</>;
 }else if(panel.kind==="vendor"){
 const v=data.vendors.find(v=>v.id===panel.id);if(!v)return null;title=t("vendorDetails");const bills=data.purchaseBills.filter(b=>b.vendorId===v.id);content=<><h2>{v.name}</h2><p className="muted">{v.city}</p><div className="detail-metrics"><FieldPair label={t("totalPurchases")}>{money(bills.reduce((s,b)=>s+b.total,0))}</FieldPair><FieldPair label={t("outstanding")}>{money(bills.reduce((s,b)=>s+b.total-b.paid,0))}</FieldPair></div><h3>{t("purchaseBills")}</h3>{bills.length?bills.map(b=><div className="list-row" key={b.id}><span>{b.id}<small>{date(b.date,lang)}</small></span><span><strong>{money(b.total)}</strong><small>{t("paid")}: {money(b.paid)}</small></span></div>):<p>{t("noBills")}</p>}<h3>{t("products")}</h3>{data.products.filter(p=>p.vendorId===v.id).map(p=><button key={p.id} className="list-row" onClick={()=>open({kind:"product",id:p.id})}><span>{p.name}</span><ArrowUpRight size={14}/></button>)}</>;
 }else if(panel.kind==="product"){
 const p=data.products.find(p=>p.id===panel.id);if(!p)return null;title=t("productDetails");const insight=data.insights.find(i=>i.targetId===p.id)??{...data.insights[1],id:`STOCK-${p.id}`,targetId:p.id,title:{en:`Restock ${p.name}`,hi:`${p.name} का स्टॉक भरें`,hinglish:`${p.name} restock karein`},summary:{en:p.sku,hi:p.sku,hinglish:p.sku},recommendation:{en:`Review a purchase of ${Math.max(0,p.reorderLevel*2-p.stock)} units.`,hi:`${Math.max(0,p.reorderLevel*2-p.stock)} यूनिट की खरीद पर विचार करें।`,hinglish:`${Math.max(0,p.reorderLevel*2-p.stock)} units ki purchase review karein.`}};content=<><span className="product-icon large"><Package size={30}/></span><h2>{p.name}</h2><p className="mono muted">{p.sku}</p><Badge status={stockStatus(p)}/><div className="field-grid"><FieldPair label={t("currentStock")}>{p.stock} {t("units")}</FieldPair><FieldPair label={t("reorderLevel")}>{p.reorderLevel}</FieldPair><FieldPair label={t("velocity")}>{p.dailySales} {t("perDay")}</FieldPair><FieldPair label={t("daysCover")}>{Math.floor(p.stock/p.dailySales)}</FieldPair></div><FieldPair label={t("vendor")}>{data.vendors.find(v=>v.id===p.vendorId)?.name}</FieldPair><p className="muted">{t("stockAdvice")}</p><div className="detail-insight"><h3>{t("recommended")}</h3><p>{insight.recommendation[lang]}</p><ActionForm insight={insight}/></div></>;
 }else if(panel.kind==="document"){
 const d=[...local.uploadedDocuments,...data.documents].find(d=>d.id===panel.id);if(!d)return null;title=t("documentDetails");content=<><div className="file-icon large"><FileText size={28}/></div><h2 className="break-word">{d.name}</h2><Badge status={d.status==="completed"?"completed":"pending"}>{t(d.status==="completed"?"processed":"reviewStatus")}</Badge><FieldPair label={t("type")}>{d.format}</FieldPair><FieldPair label={t("uploaded")}>{date(d.uploaded,lang)} 2026</FieldPair><div className="detail-insight"><p>{t(d.id.startsWith("DOC-UP-")?"simulationNote":"sampleData")}</p>{d.relatedId?.startsWith("INV-")&&<Button onClick={()=>open({kind:"invoice",id:d.relatedId!})}>{t("invoiceDetails")}<ArrowUpRight size={14}/></Button>}{d.relatedId?.startsWith("PRD-")&&<Button onClick={()=>open({kind:"product",id:d.relatedId!})}>{t("productDetails")}<ArrowUpRight size={14}/></Button>}{d.relatedId?.startsWith("EXP-")&&<FieldPair label={t("amount")}>{money(data.expenses.find(e=>e.id===d.relatedId)?.amount??0)}</FieldPair>}</div>{d.insightIds.map(id=>{const i=data.insights.find(i=>i.id===id);return i?<button className="list-row" key={id} onClick={()=>open({kind:"evidence",id:i.evidenceIds.join(",")})}><span>{i.title[lang]}</span><ArrowUpRight size={16}/></button>:null;})}</>;
 }else if(panel.kind==="action"){
 const insight=data.insights.find(i=>i.id===panel.id);if(!insight)return null;title=t(insight.action);content=<><h2>{insight.title[lang]}</h2><p>{insight.recommendation[lang]}</p><p className="muted">{t("reminderDescription")}</p><ActionForm key={insight.id} insight={insight}/></>;
 }else if(panel.kind==="actions"){
 title=t("actionCenter");content=<><p className="muted">{t("allLocal")}</p>{local.actions.length?local.actions.map(a=>{const i=data.insights.find(i=>i.id===a.insightId);return <Card className="action-record" key={a.id}><Badge status={a.status}/><h3>{i?.title[lang]??a.note}</h3>{a.note&&<p>{a.note}</p>}<small className="muted">{t("created")} {date(a.createdAt,lang)}</small>{a.status==="open"&&<Button onClick={()=>app.completeAction(a.id)}><CheckCircle2 size={15}/>{t("completeAction")}</Button>}</Card>;}):<EmptyState title={t("noActions")} description={t("noActionsNote")}><Link className="button primary" href="/insights" onClick={close}>{t("viewInsights")}</Link></EmptyState>}</>;
 }else if(panel.kind==="more"){
 title=t("more");content=<nav className="more-navigation">{[...navItems,{route:"settings" as const,icon:Plus}].map(({route,icon:Icon})=><Link key={route} href={routeHref(route)} onClick={close}><Icon size={20}/>{t(route)}</Link>)}</nav>;
 }else if(panel.kind==="help"){
 title=t("help");content=<><h2>VyaparAI</h2><p>{t("tagline")}</p><div className="detail-insight">{t("helpText")}</div><p>{t("privacyNote")}</p><Link className="button primary" href="/assistant" onClick={close}>{t("askCopilot")}<ArrowUpRight size={15}/></Link></>;
 }else if(panel.kind==="reset"){
 title=t("resetTitle");content=<><p>{t("resetNote")}</p><div className="button-row"><Button onClick={close}>{t("cancel")}</Button><Button variant="danger" onClick={app.reset}>{t("resetConfirm")}</Button></div></>;
 }else if(panel.kind==="search"){title=t("search");content=<GlobalSearch/>;}
 return <Drawer title={title} onClose={close}>{content}</Drawer>;
}
function ActionForm({insight}:{insight:Insight}){const {t,createAction,local}=useApp();const [note,setNote]=useState("");const existing=local.actions.some(a=>a.insightId===insight.id&&a.status==="open");return <form className="action-form" onSubmit={e=>{e.preventDefault();createAction(insight,note||insight.targetId);}}><label>{t("note")}<textarea rows={3} maxLength={500} value={note} onChange={e=>setNote(e.target.value)} placeholder={t("reminderNote")}/></label><Button variant="primary" type="submit">{t(existing?"actionCenter":insight.action)}<ArrowUpRight size={15}/></Button><small className="muted">{t("allLocal")}</small></form>;}
function GlobalSearch(){const {data,t,open}=useApp();const [query,setQuery]=useState("");if(!data)return null;const q=query.trim().toLowerCase();const results=[...data.invoices.map(i=>({kind:"invoice" as const,id:i.id,name:`${i.id} · ${data.customers.find(c=>c.id===i.customerId)?.name}`})),...data.customers.map(c=>({kind:"customer" as const,id:c.id,name:c.name})),...data.products.map(p=>({kind:"product" as const,id:p.id,name:p.name}))].filter(v=>q&&v.name.toLowerCase().includes(q)).slice(0,20);return <><SearchField value={query} onChange={setQuery} placeholder={t("searchPlaceholder")}/>{results.length?results.map(r=><button className="list-row" key={r.id} onClick={()=>open({kind:r.kind,id:r.id})}><Search size={16}/><span>{r.name}</span><ArrowUpRight size={14}/></button>):<EmptyState title={q?t("noResults"):t("search")} description={q?t("trySearch"):t("searchPlaceholder")}/>}</>;}
