"use client";
import { createContext, useCallback, useContext, useEffect, useState, type ReactNode } from "react";
import type { BusinessData, Insight, Language, LocalState, InsightStatus, Document, Conversation } from "@/lib/types";
import { translate, type TranslationKey } from "@/lib/i18n";
import { businessService } from "@/lib/services";
type Panel = {kind:"invoice"|"customer"|"vendor"|"product"|"document"|"evidence"|"action";id:string}|{kind:"actions"|"search"|"more"|"help"|"reset"};
const initial:LocalState={language:"en",insightStatuses:{},actions:[],uploadedDocuments:[],conversations:[]};
const storageKey="vyaparai-demo-v1";
interface AppContextValue {data:BusinessData|null;local:LocalState;t:(key:TranslationKey,vars?:Record<string,string|number>)=>string;lang:Language;setLanguage:(lang:Language)=>void;panel:Panel|null;open:(p:Panel)=>void;close:()=>void;notify:(key:TranslationKey)=>void;toast:string|null;clearToast:()=>void;status:(id:string)=>InsightStatus;setStatus:(id:string,status:InsightStatus)=>void;createAction:(insight:Insight,note:string)=>void;completeAction:(id:string)=>void;addDocument:(doc:Document)=>void;saveConversation:(c:Conversation)=>void;reset:()=>void;demoState:"normal"|"loading"|"error"|"empty";setDemoState:(s:"normal"|"loading"|"error"|"empty")=>void;reload:()=>void}
const AppContext=createContext<AppContextValue|null>(null);
export function AppProvider({children}:{children:ReactNode}){
 const [data,setData]=useState<BusinessData|null>(null);const [local,setLocal]=useState<LocalState>(initial);const [ready,setReady]=useState(false);const [panel,setPanel]=useState<Panel|null>(null);const [toast,setToast]=useState<TranslationKey|null>(null);const [demoState,setDemoState]=useState<AppContextValue["demoState"]>("normal");
 const reload=useCallback(()=>{setDemoState("normal");businessService.load().then(setData).catch(()=>setDemoState("error"));},[]);
 useEffect(()=>{let active=true;businessService.load().then(result=>{if(!active)return;setData(result);try{const raw=localStorage.getItem(storageKey);if(raw){const s=JSON.parse(raw) as Partial<LocalState>;if(["en","hi","hinglish"].includes(s.language??"")&&Array.isArray(s.actions)&&Array.isArray(s.uploadedDocuments)&&Array.isArray(s.conversations)&&s.insightStatuses&&typeof s.insightStatuses==="object")setLocal(s as LocalState);}}catch{/* A corrupt or unavailable store falls back to the original demo. */}setReady(true);}).catch(()=>setDemoState("error"));return()=>{active=false;};},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem(storageKey,JSON.stringify(local));}catch{/* The app remains usable if storage is unavailable. */}document.documentElement.lang=local.language==="hi"?"hi":local.language==="hinglish"?"hi-Latn":"en";},[local,ready]);
 const t=(key:TranslationKey,vars?:Record<string,string|number>)=>translate(local.language,key,vars);
 const value:AppContextValue={data,local,t,lang:local.language,setLanguage:language=>setLocal(s=>({...s,language})),panel,open:setPanel,close:()=>setPanel(null),notify:setToast,toast:toast?t(toast):null,clearToast:()=>setToast(null),status:id=>local.insightStatuses[id]??"open",setStatus:(id,status)=>{setLocal(s=>({...s,insightStatuses:{...s.insightStatuses,[id]:status}}));setToast(status==="handled"?"insightHandled":status==="dismissed"?"insightDismissed":"restored");},createAction:(insight,note)=>{if(local.actions.some(a=>a.insightId===insight.id&&a.status==="open")){setToast("reminderExists");setPanel({kind:"actions"});return;}setLocal(s=>({...s,actions:[{id:crypto.randomUUID(),insightId:insight.id,kind:insight.action,status:"open",createdAt:new Date().toISOString(),note},...s.actions]}));setToast("actionCreated");setPanel({kind:"actions"});},completeAction:id=>{setLocal(s=>({...s,actions:s.actions.map(a=>a.id===id?{...a,status:"completed"}:a)}));setToast("actionComplete");},addDocument:doc=>setLocal(s=>({...s,uploadedDocuments:[doc,...s.uploadedDocuments]})),saveConversation:c=>setLocal(s=>({...s,conversations:[c,...s.conversations.filter(v=>v.id!==c.id)]})),reset:()=>{setLocal({...initial,language:local.language});setDemoState("normal");setPanel(null);setToast("resetDone");},demoState,setDemoState,reload};
 return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
}
export function useApp(){const context=useContext(AppContext);if(!context)throw new Error("AppProvider is required");return context;}
