"use client";
import { ArrowDown, ArrowUpRight, Check, ChevronRight, Circle, Inbox, Search, X, type LucideIcon } from "lucide-react";
import { useEffect, useRef, type ButtonHTMLAttributes, type CSSProperties, type ReactNode } from "react";
import { useApp } from "@/components/app-provider";
import type { TranslationKey } from "@/lib/i18n";
export function Button({children,variant="secondary",className="",...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"primary"|"secondary"|"ghost"|"danger"}){return <button className={`button ${variant} ${className}`} {...props}>{children}</button>;}
export function IconButton({icon:Icon,label,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{icon:LucideIcon;label:string}){return <button className="icon-button" title={label} aria-label={label} {...props}><Icon size={19}/></button>;}
export function Card({children,className="",style,onClick}:{children:ReactNode;className?:string;style?:CSSProperties;onClick?:()=>void}){return <section className={`card ${className}`} style={style} onClick={onClick}>{children}</section>;}
export function PageHeading({title,subtitle,children}:{title:string;subtitle:string;children?:ReactNode}){return <div className="page-heading"><div><h1>{title}</h1><p>{subtitle}</p></div>{children&&<div className="heading-actions">{children}</div>}</div>;}
export function Badge({status,children}:{status:string;children?:ReactNode}){const {t}=useApp();const good=["paid","inStock","completed","active","handled"].includes(status);return <span className={`badge status-${status}`}>{good?<Check size={12}/>:<Circle size={6} fill="currentColor"/>}{children??t(status as TranslationKey)}</span>;}
export function MetricCard({label,value,detail,trend,icon:Icon}:{label:string;value:ReactNode;detail?:string;trend?:string;icon?:LucideIcon}){return <div className="metric"><div className="metric-label">{label}{Icon&&<Icon size={16}/>}</div><strong>{value}</strong><div className="metric-detail">{trend&&<span className="trend"><ArrowUpRight size={13}/>{trend}</span>}{detail}</div></div>;}
export function SearchField({value,onChange,placeholder}:{value:string;onChange:(s:string)=>void;placeholder:string}){const {t}=useApp();return <label className="search-field"><Search size={17}/><input aria-label={placeholder} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>{value&&<button type="button" aria-label={t("clearFilters")} onClick={()=>onChange("")}><X size={15}/></button>}</label>;}
export function EmptyState({title,description,children}:{title:string;description:string;children?:ReactNode}){return <div className="empty-state"><div className="empty-icon"><Inbox size={26}/></div><h3>{title}</h3><p>{description}</p>{children}</div>;}
export function Drawer({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){const {t}=useApp();const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const dialog=ref.current;const previous=document.activeElement as HTMLElement|null;dialog?.showModal();const overflow=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{dialog?.close();document.body.style.overflow=overflow;previous?.focus();};},[]);return <dialog ref={ref} className={`drawer ${wide?"wide":""}`} aria-labelledby="drawer-title" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)onClose();}}}><div className="drawer-header"><h2 id="drawer-title">{title}</h2><IconButton icon={X} label={t("close")} onClick={onClose}/></div><div className="drawer-body">{children}</div></dialog>;}
export function SectionHeading({title,description,action}:{title:string;description?:string;action?:ReactNode}){return <div className="section-heading"><div><h2>{title}</h2>{description&&<p>{description}</p>}</div>{action}</div>;}
export function TextLink({children,onClick}:{children:ReactNode;onClick:()=>void}){return <button className="text-link" onClick={onClick}>{children}<ChevronRight size={15}/></button>;}
export function DataTable({headers,children}:{headers:string[];children:ReactNode}){return <div className="table-scroll" tabIndex={0}><table><thead><tr>{headers.map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;}
export function FieldPair({label,children}:{label:string;children:ReactNode}){return <div className="field-pair"><span>{label}</span><strong>{children}</strong></div>;}
export function Change({value}:{value:number}){return <span className={`change ${value>0?"up":"down"}`}>{value>0?<ArrowUpRight size={14}/>:<ArrowDown size={14}/>} {Math.abs(value).toFixed(1)}%</span>;}
